// File generated by MineTweakerRecipeMaker
//                     READ THIS HEADER BEFORE EDITING ANYTHING
// ================================================================================
//     This file is read and changed by the mod.
//     If you remove/edit any of the markers, IT WILL STOP WORKING!
//     If you want to make manual edits, make a backup of this file!
//     Markers look like this: "//#MARKER something"
//     They indicate where calls should be placed, so that MineTweaker does them in the correct order.
//     Removes come first, then stuff is added.
// ================================================================================
//

// ================================================================================
//#MARKER REMOVE

// ================================================================================
//#MARKER REMOVE SHAPELESS
recipes.removeShapeless(<minecraft:bread>, [<ore:listAllseed>, <Natura:barleyFood>, <ore:listAllseed>]);

// ================================================================================
//#MARKER REMOVE SHAPED
recipes.removeShaped(<minecraft:cookie> * 8, [[<minecraft:wheat>, <minecraft:dye:3>, <minecraft:wheat>]]);

// ================================================================================
//#MARKER ADD

// ================================================================================
//#MARKER ADD SHAPELESS
recipes.addShapeless(<minecraft:cookie> * 4, [<ore:toolBakeware>, <ore:dyeBrown>, <ore:foodFlour>, <ore:egg>, <minecraft:sugar>]);
recipes.addShapeless(<Natura:barley.seed>, [<ore:listAllseed>]);

// ================================================================================
//#MARKER ADD SHAPED
recipes.addShaped(<Natura:barleyFood:1>, [[<ore:toolMortarandpestle>, <ore:listAllseed>]]);

